//! DWG AppInfo section writer.
//!
//! Writes the application info section (R2004+) containing
//! version, comment, and product information strings.
//!
//! Mirrors ACadSharp's `DwgAppInfoWriter`.

use crate::error::Result;
use crate::io::dwg::writer::stream_writer::IDwgStreamWriter;
use crate::io::dwg::writer::stream_writer_base::DwgStreamWriterBase;
use crate::types::DxfVersion;

/// Writer for the DWG AppInfo section.
pub struct DwgAppInfoWriter {
    version: DxfVersion,
}

impl DwgAppInfoWriter {
    /// Create a new app info writer.
    pub fn new(version: DxfVersion) -> Self {
        Self { version }
    }

    /// Write the AppInfo section, returning the raw section bytes.
    pub fn write(&self) -> Result<Vec<u8>> {
        let mut writer = DwgStreamWriterBase::new(self.version);

        let version_str = env!("CARGO_PKG_VERSION");

        let empty_checksum = [0u8; 16];

        // UInt32 4: class_version (default: 3)
        writer.write_int(3)?;
        // String: App info name
        writer.write_text_unicode("AppInfoDataList")?;
        // UInt32 4: num strings (default: 3)
        writer.write_int(3)?;

        // Byte[] 16: Version data checksum (zeroes)
        writer.write_bytes(&empty_checksum)?;
        // String: Version
        writer.write_text_unicode(version_str)?;

        // Byte[] 16: Comment data checksum (zeroes)
        writer.write_bytes(&empty_checksum)?;
        // String: Comment
        writer.write_text_unicode("Generated by acadrust")?;

        // Byte[] 16: Product data checksum (zeroes)
        writer.write_bytes(&empty_checksum)?;
        // String: Product
        let product_info = format!(
            "<ProductInformation name =\"acadrust\" build_version=\"{}\" \
             registry_version=\"{}\" install_id_string=\"acadrust\" \
             registry_localeID=\"1033\"/>",
            version_str, version_str
        );
        writer.write_text_unicode(&product_info)?;

        Ok(writer.into_data())
    }
}
